name: Tremolo

options:
  bundlePrefix: app.mallet.tremolo
  deploymentTarget:
    iOS: "14.0"
  knownRegions: ["en", "Base", "ja"]

attributes:
  ORGANIZATIONNAME: Katsu Matsuda

settings:
  DEVELOPMENT_TEAM: T437NKTG46

packages:
    XyloSwift:
        url: https://github.com/katsd/xylo-swift.git
        branch: master
    ToyTerm:
        url: https://github.com/katsd/toyterm.git
        branch: main

targets:
  Tremolo:
    type: application
    platform: iOS
    sources:
      - Tremolo
      - ../Sources
    dependencies:
        - package: XyloSwift
        - package: ToyTerm
    settings:
      base:
        PRODUCT_NAME: Tremolo
        PRODUCT_BUNDLE_IDENTIFIER: app.mallet.tremolo.example
